### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by testuser7** [wgnet/webium#5]
Hi,

Setup file have fixed dependencies for old versions of selenium and nose. Is a webium compatible with new packages?

Regards,

**Comment by Khrol** [comment]
Hi,

Webium is built on top of Selenium API. So it's compatible with newest versions as well. Feel free to use it with other Selenium and Nose versions.

I'll discuss with other guys and we'll handle somehow fixed versions.

Thank you for feedback!

**Comment by Khrol** [comment]
1.0.5 released without fixed versions. nose is removed from dependencies.
